TEMPORARY workarond for "TypeError"
TypeError: 'NoneType' object cannot be interpreted as an integer
while converting dhcp_offer to bytes.
My suspicion is that some of the opts are set to `None` and dpkt
encoder cannot handle such situation.  To be investigated and replaced
by a permanent fix.

SignedOff-by: Eugene Crosser <evgenii.cherkashin@cloud.ionos.com>